// Helper to create compressed inline SVG images for clothes (No external placeholders needed)
const createFashionSvg = (bg1, bg2, label, categoryName) => {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="750" viewBox="0 0 600 750">
    <defs>
      <linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="${bg1}"/>
        <stop offset="100%" stop-color="${bg2}"/>
      </linearGradient>
    </defs>
    <rect width="100%" height="100%" fill="url(#g)"/>
    <rect x="30" y="30" width="540" height="690" rx="16" fill="none" stroke="#ffffff" stroke-opacity="0.15" stroke-width="2"/>
    <text x="300" y="360" font-family="Plus Jakarta Sans, sans-serif" font-size="22" font-weight="700" fill="#ffffff" text-anchor="middle" letter-spacing="3">${categoryName.toUpperCase()}</text>
    <text x="300" y="400" font-family="Plus Jakarta Sans, sans-serif" font-size="16" font-weight="400" fill="#e0a96d" text-anchor="middle" letter-spacing="1">${label}</text>
  </svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
};

export const INITIAL_WARDROBE_ITEMS = [
  {
    id: "item-1",
    userId: "test-user",
    imageUrl: createFashionSvg("#1e1b4b", "#4338ca", "Ivory Threadwork", "Chikankari Kurta"),
    category: "top",
    subcategory: "kurta",
    color: "white",
    colorName: "Ivory White",
    pattern: "floral embroidery",
    fabric: "cotton",
    occasion: ["college", "puja", "casual", "festival"],
    season: "all",
    vibe: "traditional",
    formality: 3,
    lastWorn: "2026-08-28T10:00:00.000Z",
    favorite: true,
    quantity: 1,
    size: "M",
    brand: "FabIndia",
    createdAt: "2026-08-01T10:00:00.000Z"
  },
  {
    id: "item-2",
    userId: "test-user",
    imageUrl: createFashionSvg("#881337", "#be123c", "High-Rise Wide Leg", "Vintage Denim Jeans"),
    category: "bottom",
    subcategory: "jeans",
    color: "blue",
    colorName: "Deep Indigo",
    pattern: "solid",
    fabric: "denim",
    occasion: ["college", "casual", "date", "travel"],
    season: "all",
    vibe: "chic",
    formality: 2,
    lastWorn: "2026-09-02T10:00:00.000Z",
    favorite: true,
    quantity: 1,
    size: "28",
    brand: "Levi's",
    createdAt: "2026-08-02T10:00:00.000Z"
  },
  {
    id: "item-3",
    userId: "test-user",
    imageUrl: createFashionSvg("#78350f", "#d97706", "Mirror Work & Tassels", "Garba Chaniya Choli Top"),
    category: "top",
    subcategory: "choli",
    color: "yellow",
    colorName: "Mustard Yellow",
    pattern: "mirror work",
    fabric: "cotton blend",
    occasion: ["garba", "diwali", "festival"],
    season: "autumn",
    vibe: "traditional",
    formality: 4,
    lastWorn: "2026-08-15T10:00:00.000Z",
    favorite: true,
    quantity: 1,
    size: "M",
    brand: "Biba",
    createdAt: "2026-08-03T10:00:00.000Z"
  },
  {
    id: "item-4",
    userId: "test-user",
    imageUrl: createFashionSvg("#064e3b", "#0d9488", "Flared Garba Skirt", "Emerald Bandhani Lehenga"),
    category: "bottom",
    subcategory: "lehenga skirt",
    color: "green",
    colorName: "Emerald Green",
    pattern: "bandhani print",
    fabric: "silk chiffon",
    occasion: ["garba", "wedding", "diwali", "festival"],
    season: "all",
    vibe: "traditional",
    formality: 5,
    lastWorn: "2026-08-10T10:00:00.000Z",
    favorite: false,
    quantity: 1,
    size: "Free Size",
    brand: "Global Desi",
    createdAt: "2026-08-04T10:00:00.000Z"
  },
  {
    id: "item-5",
    userId: "test-user",
    imageUrl: createFashionSvg("#4c1d95", "#6d28d9", "Royal Zari Border", "Kanjeevaram Silk Saree"),
    category: "dress",
    subcategory: "saree",
    color: "purple",
    colorName: "Royal Magenta Purple",
    pattern: "zari weave",
    fabric: "silk",
    occasion: ["wedding", "diwali", "puja"],
    season: "all",
    vibe: "traditional",
    formality: 5,
    lastWorn: "2026-07-20T10:00:00.000Z",
    favorite: true,
    quantity: 1,
    size: "Unstitched",
    brand: "Nalli",
    createdAt: "2026-08-05T10:00:00.000Z"
  },
  {
    id: "item-6",
    userId: "test-user",
    imageUrl: createFashionSvg("#0f172a", "#334155", "Statement Drop Earrings", "Oxidised Silver Jhumkas"),
    category: "accessory",
    subcategory: "jhumkas",
    color: "silver",
    colorName: "Antique Silver",
    pattern: "filigree",
    fabric: "alloy metal",
    occasion: ["garba", "diwali", "college", "wedding", "casual", "festival"],
    season: "all",
    vibe: "boho",
    formality: 3,
    lastWorn: "2026-09-01T10:00:00.000Z",
    favorite: true,
    quantity: 1,
    size: "One Size",
    brand: "Tribe Amrapali",
    createdAt: "2026-08-06T10:00:00.000Z"
  },
  {
    id: "item-7",
    userId: "test-user",
    imageUrl: createFashionSvg("#7c2d12", "#c2410c", "Handcrafted Leather", "Embroidered Kolhapuri Chappals"),
    category: "footwear",
    subcategory: "kolhapuris",
    color: "tan",
    colorName: "Tan Brown",
    pattern: "braided leather",
    fabric: "leather",
    occasion: ["college", "garba", "casual", "festival"],
    season: "summer",
    vibe: "ethnic chic",
    formality: 3,
    lastWorn: "2026-08-30T10:00:00.000Z",
    favorite: true,
    quantity: 1,
    size: "38",
    brand: "Needledust",
    createdAt: "2026-08-07T10:00:00.000Z"
  },
  {
    id: "item-8",
    userId: "test-user",
    imageUrl: createFashionSvg("#15803d", "#166534", "Ribbed Knit Tank", "Olive Green Crop Top"),
    category: "top",
    subcategory: "crop top",
    color: "green",
    colorName: "Olive Green",
    pattern: "solid ribbed",
    fabric: "cotton elastane",
    occasion: ["college", "casual", "date", "party"],
    season: "summer",
    vibe: "minimal",
    formality: 2,
    lastWorn: "2026-09-04T10:00:00.000Z",
    favorite: false,
    quantity: 1,
    size: "S",
    brand: "Zara",
    createdAt: "2026-08-08T10:00:00.000Z"
  },
  {
    id: "item-9",
    userId: "test-user",
    imageUrl: createFashionSvg("#991b1b", "#dc2626", "Classic Block Print", "Crimson Anarkali Suit"),
    category: "dress",
    subcategory: "anarkali",
    color: "red",
    colorName: "Ruby Crimson Red",
    pattern: "block print",
    fabric: "chiffon silk",
    occasion: ["diwali", "wedding", "puja", "festival"],
    season: "all",
    vibe: "traditional",
    formality: 4,
    lastWorn: "2026-07-15T10:00:00.000Z",
    favorite: true,
    quantity: 1,
    size: "M",
    brand: "Anita Dongre",
    createdAt: "2026-08-09T10:00:00.000Z"
  },
  {
    id: "item-10",
    userId: "test-user",
    imageUrl: createFashionSvg("#1e293b", "#475569", "Block Heel Strappy Sandals", "Nude Block Heels"),
    category: "footwear",
    subcategory: "heels",
    color: "beige",
    colorName: "Nude Beige",
    pattern: "solid",
    fabric: "faux suede",
    occasion: ["party", "wedding", "date", "college"],
    season: "all",
    vibe: "chic",
    formality: 4,
    lastWorn: "2026-08-25T10:00:00.000Z",
    favorite: false,
    quantity: 1,
    size: "38",
    brand: "H&M",
    createdAt: "2026-08-10T10:00:00.000Z"
  }
];
